
services:
  web:
    build: .
    command: web
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=forex_trading_project.settings
    volumes:
      - .:/app

  worker:
    build: .
    command: worker
    depends_on:
      - redis
    volumes:
      - .:/app

  beat:
    build: .
    command: beat
    depends_on:
      - redis
    volumes:
      - .:/app

  ai:
    build: .
    command: ai
    depends_on:
      - redis
    volumes:
      - .:/app
    dns:
      - 8.8.8.8

  redis:
    image: redis:latest
    ports:
      - "6379:6379"