# Generated by Django 5.1.3 on 2024-12-01 09:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('accuracy', models.FloatField(default=0)),
                ('total_trades', models.IntegerField(default=0)),
                ('profitable_trades', models.IntegerField(default=0)),
                ('last_trained', models.DateTimeField(auto_now=True)),
                ('model_path', models.CharField(max_length=255)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('demo_balance', models.DecimalField(decimal_places=2, default=10000, max_digits=15)),
                ('meta_api_token', models.CharField(blank=True, max_length=255)),
                ('account_id', models.CharField(blank=True, max_length=100)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=15)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('is_ai_trade', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('profit_loss', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CopyTrading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('copy_amount_percentage', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(1)])),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='trading.userprofile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='trading.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=5, max_digits=15)),
                ('high', models.DecimalField(decimal_places=5, max_digits=15)),
                ('low', models.DecimalField(decimal_places=5, max_digits=15)),
                ('close', models.DecimalField(decimal_places=5, max_digits=15)),
                ('volume', models.IntegerField()),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingpair')),
            ],
            options={
                'indexes': [models.Index(fields=['pair', 'timestamp'], name='trading_mar_pair_id_bd3150_idx')],
            },
        ),
    ]
