# Generated by Django 5.1.3 on 2024-12-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apikey',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
