# Generated by Django 5.1.3 on 2024-12-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_news_content_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='position_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
